baseURL = 'https://ngpu.org/'
languageCode = 'uk-UA'
defaultContentLanguage = 'uk'
title = 'Укрнафтогазпрофспілка'
theme = 'mainroad'
summaryLength = 36

[Params]
mainSections = ['posts']
customCSS = ['css/ngpu-layout.css']
dateformat = '02.01.2006'
date_format = '02.01.2006'

[Params.sidebar]
home = false
list = 'right'
single = 'right'
widgets = ['recent', 'categories', 'taglist']
