baseURL = 'https://ngpu.org/'
languageCode = 'en-us'
title = 'NGPU'
theme = "mainroad"
[Params]
  [Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["recent", "categories", "taglist"]
